# Usando Java 21
FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline


COPY src ./src

RUN mvn clean package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "target/indaiatubapalete-0.0.1-SNAPSHOT.jar"]